#define CHRONICLE_MSGTYPE_FORK          1001
#define CHRONICLE_MSGTYPE_BLOCK         1002
#define CHRONICLE_MSGTYPE_TX_TRACE      1003
#define CHRONICLE_MSGTYPE_ABI_UPD       1004
#define CHRONICLE_MSGTYPE_ABI_REM       1005
#define CHRONICLE_MSGTYPE_ABI_ERR       1006
#define CHRONICLE_MSGTYPE_TBL_ROW       1007
#define CHRONICLE_MSGTYPE_ENCODER_ERR   1008
