name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #install gnupg
    # - name: gnupg
    #   run: |
    #       sudo apt install -y gnupg software-properties-common
    #       wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null
    #       sudo apt-key add -

    #add repository
    # - name: add repository
    #   run: sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

    # install dependencies
    - name: dependencies
      run: |
           sudo apt update
           sudo apt install -y git g++-8 cmake libssl-dev libgmp-dev zlib1g-dev
           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

    # install boost
    - name: boost
      run: |
           wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
           tar -xvzf boost_1_67_0.tar.gz
           cd boost_1_67_0
           ./bootstrap.sh
           ./b2 install 
           cd ..

    #update submodules
    - name: git submodule update
      run: git submodule --init --recursive

    # build project
    - name: mkdir
      run: |
          mkdir -p build
          cd build
          cmake ..
          make
    